<h3>Controllers</h3>
<div class="app-controllers">
<?php foreach ($this->controllers as $controller): ?>
    <p><?php echo ucfirst($controller)?>Controller</p>
    <div>
        <?php echo $this->renderComponent('ctrl', 'actionList', array(
            'app' => $this->app,
            'controller' => $controller
        ));?>
    </div>
<?php endforeach;?>
</div>
<a class="create-controller" style="float:right;" href="javascript:void(false);" title="Create Controller" data-action="dialog" data-source="{{url('ctrl-new')}}?app={{app}}">New</a>
<script>


$('a.create-controller').on('dialogSuccess', function(){
	$('.appcontent').load('{{url("app-default", ["app": $this.app, "action": "controllers"])}}');
});
$('.app-controllers .rad-selectable').radselectable();
$('.app-controllers').accordion({
	collapsible: true,
	autoHeight: false
});
</script>

