<h3>Controllers</h3>
<div class="app-controllers">
<?php foreach ($this->controllers as $controller): ?>
    <p><?php echo ucfirst($controller)?>Controller</p>
    <div>
        <?php echo $this->renderComponent('ctrl', 'actionList', array(
            'app' => $this->app,
            'controller' => $controller
        ));?>
    </div>
<?php endforeach;?>
</div>
<a style="float:right;" href="#">New</a>
<script>

$('.app-controllers .rad-selectable').radselectable();
$('.app-controllers').accordion({
	collapsible: true
});
</script>

