<div style="width: 400px;">
    <form class="automatic" action="{{url('app-create')}}">
        <h3>General</h3>
        <p>
            <label>Application Name<span class="ex">Example: MyApplication</span><br/>
                <input type="text"  name="app[name]"/>
            </label>
        </p>
        <p>
            <label>Front Controller<span class="ex">Example: myapp.php</span><br/>
                <input type="text" name="app[fc]"/>
            </label> <br/>
            <label>
                <input type="checkbox" name="app[withdev]" checked="checked" value="1"/> With DEV environment
            </label> 
        </p>
        <h3>Additional</h3>
        <p>
            <label>Description<span class="ex">Example: My application is very cool</span><br/>
                <textarea style="height:100px" name="app[desc]"></textarea>
            </label>
        </p>
        <div class="actions">
            <button type="submit">Create</button>
        </div>
    </form>
</div>