<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Candle Demo Site</title>
<link type="text/css" rel="stylesheet" href="/css/layout.css" />

</head>
<body>
    <div id="maincontainer">

        <div id="topsection">
            <div class="innertube">
                <h1>Candle Demo</h1>
                <small><?php echo CANDLE_ENVIRONMENT == 'prod' ? 'production mode' : '<span style="color:darkred">development mode</span>'?></small>
            </div>
        </div>

        <div id="contentwrapper">
            <div id="contentcolumn">
                <div class="innertube">
                    <?php echo $this->candle_content; ?>
                </div>
            </div>
        </div>

        <div id="leftcolumn">
            <div class="innertube">Menu</div>
        </div>

        <div id="footer">Footer</div>

    </div>
</body>
</html>
