<div class="panel-body">
    <h3 class="panel-title">{{method.name}}()</h3>
    <br/>
    <pre class="prettyprint lang-php rad-code" style="width: 90%;">{{method.source}}</pre>
    <?php if($this->tpl): ?>
        <br /><br/>
        <h3 class="panel-title">Template {{tpl.fileName}}</h3>
        <br/>
        <pre class="prettyprint lang-html rad-code" style="width: 90%;"><?php echo htmlspecialchars($this->tpl['source']); ?></pre>
    <?php else: ?>
        <p style="margin: 10px; padding: 10px;" class="ui-state-error">No template found</p>
    <?php endif; ?>
</div>
<script>
prettyPrint();
</script>
