<div class="panel-body white content">
	<h1>Hello to Candle RAD</h1>
	<p>This is a Rapid Application Development environment for Candle framework</p>
	<p></p>
	<h1>Installed applications</h1>
	<ul>
	<?php echo $this->renderComponent('app', 'installedList'); ?>
		
	</ul>
	<h1>Capabilities</h1>
	Tested successfully on
	<ul>
		<li>Firefox</li>
		<li>Chrome</li>
		<li>Opera</li>
		<li>Safary</li>
		<li>Internet Explorer 6+</li>
	</ul>
	<h1>Requirements</h1>
	<ul>
		<li>Be creative</li>
		<li>Be smart and use it</li>
	</ul>
</div>