<h1>HTTP 500 - Internel Server Error</h1>
<p>An internal server error occured while trying to handle the request</p>
<?php if (CANDLE_ENVIRONMENT == 'dev'):?>
<?php 
    $exClass = get_class($this->exception);
    $parts = explode('\\', $exClass);
    $exClass = array_pop($parts);
?>
    <div style="background: silver;">
        <h3>Uncought <span style="color: maroon;"><?php echo $exClass; ?></span>: "<?php echo $this->exception->getMessage(); ?>"</h3>
        <pre style="font-size: 11px;"><?php 
            $trace =  $this->exception->getTraceAsString();
            echo str_replace(CANDLE_INSTALL_DIR, '', $trace);
        ?></pre>
    </div>
<?php endif; ?>