<html>
    <head>
        
		<!-- jQuery and jQuery UI -->
        <script src="/rad/js/lib/jquery/jquery-1.7.1.min.js" type="text/javascript" ></script>
        <script src="/rad/js/lib/jquery/jquery-ui-1.8.17.custom.min.js" type="text/javascript" ></script>
		<link rel="stylesheet" type="text/css" media="all" href="/rad/js/lib/jquery/themes/slimp/jquery-ui-slimp.css" />
		
		<!-- jQuery Panels -->
        <script src="/rad/js/lib/jquery.panels/jquery.panels.js" type="text/javascript" ></script>
		<link rel="stylesheet" type="text/css" media="all" href="/rad/js/lib/jquery.panels/css/jquery.panels.css" />
		<!-- jQuery Mousewheel -->
		<script src="/rad/js/lib/jquery.mousewheel.min.js" type="text/javascript"></script>
		<!-- jQuery jScrollPane -->
		<script src="/rad/js/lib/jquery.jscrollpane/jquery.jscrollpane.js" type="text/javascript"></script>
		<link rel="stylesheet" type="text/css" media="all" href="/rad/js/lib/jquery.jscrollpane/css/jquery.jscrollpane.css" />
		<!-- jQuery Selectmenu -->
		<script src="/rad/js/lib/jquery.selectmenu/jquery.ui.selectmenu.js" type="text/javascript"></script>
		<link rel="stylesheet" type="text/css" media="all" href="/rad/js/lib/jquery.selectmenu/css/jquery.ui.selectmenu.css" />
		
		<!-- Rad -->
		<script src="/rad/js/rad.js" type="text/javascript"></script>
		<script src="/rad/js/rad.panels.js" type="text/javascript"></script>
		<link rel="stylesheet" type="text/css" media="all" href="/rad/css/rad.css" />
		<link rel="stylesheet" type="text/css" media="all" href="/rad/css/rad-reset.css" />
				
				
    </head>
    <body>
			<div id="panels">
					

			</div>
		</body>	
</html>