<ul class="app-list" style="padding: 0">
    <?php foreach ($this->apps as $app): ?>
        <li class="app"><a href="#" class="ajax" data-target="panel-workarea .panel-body" data-source="widget/appdetails" data-data="<?php echo $app; ?>"><?php echo ucfirst($app)?></a></li>
    <?php endforeach;?>
</ul>
<a class="create-new-app" href="#" title="Create Application"  data-action="dialog" data-source="{{url('app-new')}}">Create New Application</a>
<script>
$('ul.app-list .app').button().find('a').css({
	lineHeight: '80px',
	height: '80px',
	display: 'inline-block',
	width: '80px'
});

$('a.create-new-app').on('dialogSuccess', function(){
	rad.panels.switchPanelTo($(this).closest('.ui-panel'), 'workarea');
}).on('dialogError', function(event, response){
	console.log(response);
	rad.alert(response.responseText);
	event.handled = true;
})
</script>