
<h3>Actions</h3>
<ul class="rad-selectable" style="background: #505050;">
<?php foreach($this->methods['actions'] as $action): ?>
    <li><?php echo $action?></li>
<?php endforeach; ?>
</ul>
<a style="float:right;" href="#">New</a><br/>
<hr/>
<h3>Components</h3>
<ul class="rad-selectable" style="background: #505050;">
<?php foreach($this->methods['components'] as $component): ?>
    <li><?php echo $component?></li>
<?php endforeach; ?>
</ul>
<a style="float:right;" href="#">New</a>